name: Deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push to gh-pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
