name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test code
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Test code
        run: npm run test
